FROM node:22-alpine AS build
WORKDIR /app

COPY src/kubernet-dashboard/package.json ./
RUN npm install

COPY src/kubernet-dashboard/ ./
RUN npm run build

FROM nginx:1.28-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY src/kubernet-dashboard/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist ./

EXPOSE 80
