FROM node:22-alpine AS build
WORKDIR /app

COPY src/kubernet-dashboard/package.json ./
RUN npm install

COPY src/kubernet-dashboard/ ./
RUN npm run build

FROM nginx:1.28-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY src/kubernet-dashboard/default.conf.template /etc/nginx/templates/default.conf.template
COPY src/kubernet-dashboard/docker-entrypoint.sh /docker-entrypoint.sh
COPY --from=build /app/dist ./

RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
